### ISSUE TITLE
Force-play button inside the `/queue` slash command doesn't work.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#115]
### Description

If you try choosing a song from the queue using the `/queue` slash command and then try to force-play it using the dedicated button, the queue is cleared and no song is played.

The expected behavior is that the button will change the index of the song to prioritize it and then skip the currently playing song to force-play the one of your choice. The queue should not be cleared.

I hope this will help you understand the bug and eventually squish it!

**Comment by furtidev** [comment]
Can you assign me to it? I'll work on it tomorrow.

**Comment by hitblast** [comment]
@furtidev Sure!

**Comment by furtidev** [comment]
> @furtidev Sure!

@hitblast I've checked and I can't seem to re-create this issue. It works perfectly fine on my machine. 🤔

**Comment by hitblast** [comment]
@furtidev Looks like it was accidental. Close it as unplanned...
