### ISSUE TITLE
Light mode in homepage

### ISSUE THREAD

**Issue by ItsRoy69** [IgKniteDev/IgKnite#150]
### Description

When we visit the website, we see the website with dark mode, we can add light mode feature.
Here

### Screenshots

![image](https://user-images.githubusercontent.com/78967360/204119730-252ffdbd-8669-4238-b876-a3e8fbc0bf4a.png)

**Comment by hitblast** [comment]
@ItsRoy69 Thanks for the suggestion!

Currently a new landing page for IgKnite with a lighter outlook is in the works so I guess putting effort into making a toggle-able interface wouldn't be worth it. I would definitely like your thoughts on this.

**Comment by hitblast** [comment]
Closing the issue for now.
