### ISSUE TITLE
[bug] Buttons duplicate after pressing on a song's representation inside the `/queue` select menu.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#163]
### Description

Whenever you'll try to choose songs from the select UI menu inside the `/queue` command, everything will work perfectly fine for the first song you choose. However, as you go and choose more, the **Play** and **Remove Song** buttons will replicate over and over and eventually turn to something like the screenshot given below. This is a critical bug and needs fixing as soon as possible.

### Screenshots

<img width="619" alt="Screenshot 2022-12-30 at 8 09 45 PM" src="https://user-images.githubusercontent.com/67194380/210079310-3466b824-c6d1-401f-910d-c2b5e0b12e81.png">

**Comment by Memomer** [comment]
Can I be assigned this issue?

**Comment by hitblast** [comment]
@Memomer If you'd like to resolve the reported bug, then surely I'm assigning you on this issue. Go ahead!

**Comment by hitblast** [comment]
@Memomer Let me know about the progress on the issue if you don't mind :D

**Comment by Memomer** [comment]
> @Memomer Let me know about the progress on the issue if you don't mind. :D

Hey, actually I have been studying about aysncio and going throught the IgKnite documentations, let me know if you are okay with me learning on the way and if i am the right guy for this. Thankyou.

**Comment by hitblast** [comment]
> > @Memomer Let me know about the progress on the issue if you don't mind. :D
> 
> Hey, actually I have been studying about aysncio and going throught the IgKnite documentations, let me know if you are okay with me learning on the way and if i am the right guy for this. Thankyou.

@Memomer I don't have any problems with you learning as you go. Take your time and feel free to ask me anything! :D

**Comment by Memomer** [comment]
> > > @Memomer Let me know about the progress on the issue if you don't mind. :D
> > 
> > 
> > Hey, actually I have been studying about aysncio and going throught the IgKnite documentations, let me know if you are okay with me learning on the way and if i am the right guy for this. Thankyou.
> 
> @Memomer I don't have any problems with you learning as you go. Take your time and feel free to ask me anything! :D

Thanks, actually I am having trouble running the app on my pc,
![image](https://user-images.githubusercontent.com/107757811/215315131-5879803b-961c-4dc2-af01-367c75019795.png)
this the error comming up when I run main.py file

**Comment by hitblast** [comment]
@Memomer Are you running the bot with Python 3.11? The `Self` class is exclusive to this version.

**Comment by Memomer** [comment]
> @Memomer Are you running the bot with Python 3.11? The `Self` class is exclusive to this version.
> 
> Edit: Apparently I had forgotten to update the version requirements in the documentation so updated it just now. Sorry for the inconvenience haha.

Oh haha, no issues, so i need to make a new virtual environment and install the requirements again right?

**Comment by hitblast** [comment]
@Memomer Any updates?

**Comment by Memomer** [comment]
@hitblast Hey, I had my exams this week and a hackathon yesterday so was busy with that stuff but I am working on the bug right now. Sorry for the delay.

**Comment by hitblast** [comment]
> @hitblast Hey, I had my exams this week and a hackathon yesterday so was busy with that stuff but I am working on the bug right now. Sorry for the delay.

@Memomer Not a problem! No rush, take your time.

**Comment by Memomer** [comment]
@hitblast Hey I tried to run the bot again and its throwing the exact same issue, I reinstalled the repo files and requirements
![Screenshot from 2023-02-11 15-31-30](https://user-images.githubusercontent.com/107757811/218252163-c4a94845-f505-459c-b840-7a81e4bea519.png)

**Comment by Memomer** [comment]
For some reason even after I installed python 3.11.2 its not update on usr/bin
![image](https://user-images.githubusercontent.com/107757811/218252630-6dc4ec17-05d3-48a4-a7ea-bc7c5f316355.png)

**Comment by Memomer** [comment]
Hey @hitblast,
I enabled all the privilege access intent but the bot is not connecting for some reason.
![image](https://user-images.githubusercontent.com/107757811/218255382-b260e675-d37d-4f7c-99b3-48da6c035937.png)

**Comment by hitblast** [comment]
> Hey @hitblast,
> I enabled all the privilege access intent but the bot is not connecting for some reason.

<img width="997" alt="Screenshot 2023-02-11 at 9 45 03 PM" src="https://user-images.githubusercontent.com/67194380/218267377-c79643fd-06ce-457a-a4ea-b9b092f90ce0.png">

@Memomer are you sure that all of these are enabled?

**Comment by Memomer** [comment]
> > Hey @hitblast,
> > I enabled all the privilege access intent but the bot is not connecting for some reason.
> 
> <img alt="Screenshot 2023-02-11 at 9 45 03 PM" width="997" src="https://user-images.githubusercontent.com/67194380/218267377-c79643fd-06ce-457a-a4ea-b9b092f90ce0.png">
> 
> @Memomer are you sure that all of these are enabled?

Hey I missed some checkboxes and its working finally!!

**Comment by Memomer** [comment]
@hitblast The ui button seems to be duplicating because there is no method to verify if there is already a play/remove song button  available in music.py from class Song.queue

**Comment by hitblast** [comment]
> @hitblast The ui button seems to be duplicating because there is no method to verify if there is already a play/remove song button  available in music.py from class Song.queue
> We will need to add a method which checks if first song is played or not and doesn't generate more ui.buttons
> 

@Memomer Well have you implemented a prototype solution?

**Comment by Memomer** [comment]
> > @hitblast The ui button seems to be duplicating because there is no method to verify if there is already a play/remove song button  available in music.py from class Song.queue
> > We will need to add a method which checks if first song is played or not and doesn't generate more ui.buttons
> 
> @Memomer Well have you implemented a prototype solution?

I am actually having a tough time coding out one, maybe this is above my skill level.

**Comment by hitblast** [comment]
> > > @hitblast The ui button seems to be duplicating because there is no method to verify if there is already a play/remove song button  available in music.py from class Song.queue
> > > We will need to add a method which checks if first song is played or not and doesn't generate more ui.buttons
> > 
> > 
> > @Memomer Well have you implemented a prototype solution?
> 
> I am actually having a tough time coding out one, maybe this is above my skill level.

@Memomer Let me know if you need any assistance with any Python-related stuff. I'll try to help. :D

**Comment by hitblast** [comment]
@Memomer I think I will take over this issue. Let me know if you still would like to continue work on it.
