### ISSUE TITLE
Link redirects to the same page in https://igknition.ml/docs/hosting_preparation.html website

### ISSUE THREAD

**Issue by Memomer** [IgKniteDev/IgKnite#166]
### Description

Link redirects to the same page for the text-link, "this article from discord"

### Screenshots

![image](https://user-images.githubusercontent.com/107757811/215310677-a06df9df-f28e-4cb8-b498-e27c94f1231e.png)

### Additional information

I wasn't able to find the necessary link so I had to post it here.

**Comment by hitblast** [comment]
@Memomer Thanks for reporting! I will add the link shortly.
