### ISSUE TITLE
[FEATURE] Add configuration for managing loaded cogs.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#276]
### Description

Currently, the way the cogs are loaded is by actually interacting with the `main.py` and selecting which ones to load and which ones to unload. A central configuration for choosing the loaded cogs could be excellent in terms of self-hosting the bot for whoever wants to do it.

**Comment by iyad-f** [comment]
Hi @hitblast  i would like to work on this, although i think everything from the cogs folder should be loaded and we can add commands to unload or load an extension. We can have a discussion on what the implementation should be

**Comment by hitblast** [comment]
@iyad-f Sure! If you'd like, I can assign this issue to you. Also, I'm a bit curious on how you'd like to have conversations about this since GitHub Discussions, Discord, all are good options.

**Comment by iyad-f** [comment]
@hitblast , I am on with both but i guess discord is okay

**Comment by hitblast** [comment]
> @hitblast , I am on with both but i guess discord is okay. This is my discord username iyad8888

@iyad-f I've sent a friend request over, and also assigning this issue to you. If you have any questions or if you need help, feel free to knock.
