### ISSUE TITLE
[FEATURE] Add Automatic cog discovery | Decouple hard coded cog loading

### ISSUE THREAD

**Issue by ultralegendary** [IgKniteDev/IgKnite#281]
#### Purpose
Automatic cog discovery will read all the files present under Cog folder and make them as available cogs.
All these available cogs should be disabled by default. Bot owner/privilaged users should be allowed to view and load cogs from commands.

https://github.com/IgKniteDev/IgKnite/blob/2c94e257d817c4351036263c341cf312215cd014/main.py#L15-L22

[Nice to have] We can add support to download and load third party cogs from the comamnds for the discord bot without much effort.

**Comment by hitblast** [comment]
@ultralegendary Seems like a nice addition! Would you like to work on this?

**Comment by ultralegendary** [comment]
Hey @hitblast I would be happy to help. I will try to see how effort this would take and plan accordingly.
If I am able to get this done I will merge this feature along with #279 .
For now let the assignee be empty.

**Comment by hitblast** [comment]
> Hey @hitblast I would be happy to help. I will try to see how effort this would take and plan accordingly.
> If I am able to get this done I will merge this feature along with #279 .
> For now let the assignee be empty.

Alright, sure!

**Comment by iyad-f** [comment]
Hi, I would like to work on this

**Comment by hitblast** [comment]
@ultralegendary This issue has been completed by @iyad-f so closing.
