### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by detronetdip** [IgKniteDev/IgKnite#37]
The link for the documentation is not working. Do you have any documentation to get started. I am very exited to contribute to this project, if you have any documentation please let me know.

**Comment by hitblast** [comment]
Hello there! Thanks for showing your interest in this project. Could you please show me where the links aren't working? I have checked the visible ones and they do indeed work. 

Feel free to fork the project for now and start making your own changes. The documentation is still under work-in-progress condition so you might check out the **CONTRIBUTING.md** and **CODE_OF_CONDUCT.md** files if you want to learn more about our contribution guidelines. 

Some links related to the documentation have been given below.

Repository: https://github.com/IgKniteDev/docs
Website: https://igknition.ml/docs

**Comment by detronetdip** [comment]
Hey @hitblast  please check README file of  https://github.com/IgKniteDev/IgKnite. There is a section called `how to use?` the link is not working there.
![Screenshot from 2022-09-23 09-51-12](https://user-images.githubusercontent.com/64276906/191891820-891a8d9b-e9c3-414a-953f-111720237206.png)

**Comment by hitblast** [comment]
> Hey @hitblast please check README file of https://github.com/IgKniteDev/IgKnite. There is a section called `how to use?` the link is not working there.
> 
> ![Screenshot from 2022-09-23 09-51-12](https://user-images.githubusercontent.com/64276906/191891820-891a8d9b-e9c3-414a-953f-111720237206.png)
> 
> It is showing Deceptive site ahead. ![Screenshot from 2022-09-23 09-55-36](https://user-images.githubusercontent.com/64276906/191891996-54bcc426-31b9-49b4-9109-c3e944923852.png)

<img width="677" alt="Screen Shot 2022-09-23 at 1 12 34 PM" src="https://user-images.githubusercontent.com/67194380/191909137-40010d80-fafa-454c-a524-e6ca68e0c138.png">

Checked the repository for the documentation. The "Enforce HTTPS" option was unticked, how about you try now?
Note: The "Deceptive site ahead" warning may only show on Chrome-based web browsers.

**Comment by detronetdip** [comment]
Working fine.
Thank you
