### ISSUE TITLE
Add a selection menu inside the `/queue` command.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#38]
Instead of displaying the enqueued songs in the form of a list of strings, adding a selection menu to the view of the `/queue` command might be a more 'interactive' way to tinker with the queue system.

It must contain every enqueued song as an 'option'. Clicking each one would trigger something similar to the `/now` command; provide in-depth details about the song itself.

**Comment by prasoonmhwr** [comment]
May I take this issue

**Comment by prasoonmhwr** [comment]
@hitblast Is there any document defining the project architecture so that I can know where to start

**Comment by hitblast** [comment]
> @hitblast Is there any document defining the project architecture so that I can know where to start

Well, as of now, the documentation is still in development. However, I'll try modifying the contribution guidelines to contain the code structure for a new command. This will make things easier as you'll only need to think about the backend and not how to write a command properly :)

**Comment by prasoonmhwr** [comment]
> > @hitblast Is there any document defining the project architecture so that I can know where to start
> 
> Well, as of now, the documentation is still in development. However, I'll try modifying the contribution guidelines to contain the code structure for a new command. This will make things easier as you'll only need to think about the backend and not how to write a command properly :)

One more thing how do i test it in local as it a discord bot

**Comment by prasoonmhwr** [comment]
@hitblast I am facing this error while running in local , I have installed all the libraries mentioned in requirement.txt , I have also added the .env with the details provided above.

<img width="1108" alt="Screenshot 2022-09-30 at 9 36 22 PM" src="https://user-images.githubusercontent.com/52622674/193311760-8ee36d73-8f07-4f8f-a7a1-231769427475.png">


Am I running it correctly?

**Comment by hitblast** [comment]
@prasoonmhwr You are. Have you installed the dependencies correctly?

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr You are. Have you installed the dependencies correctly?

yes these are the only dependencies right?

python-decouple
disnake[speed,voice]
youtube-dl
spotipy

**Comment by hitblast** [comment]
> > @prasoonmhwr You are. Have you installed the dependencies correctly?
> 
> yes these are the only dependencies right?
> 
> python-decouple disnake[speed,voice] youtube-dl spotipy

Yeah. Also the library wasn't even updated in recent time. I wonder if something's wrong with your environment. Could you try re-checking the dependencies you've installed and that you're on the correct environment.

**Comment by prasoonmhwr** [comment]
@hitblast thanks for the help it was environment issue, now may it know how to inject this in a server . I mean what is the next step after this.

<img width="1018" alt="Screenshot 2022-09-30 at 10 11 44 PM" src="https://user-images.githubusercontent.com/52622674/193317705-ff24acf6-de0d-4da9-b845-8ee7306e4824.png">

**Comment by hitblast** [comment]
> @hitblast thanks for the help it was environment issue, now may it know how to inject this in a server . I mean what is the next step after this.
> 
> <img alt="Screenshot 2022-09-30 at 10 11 44 PM" width="1018" src="https://user-images.githubusercontent.com/52622674/193317705-ff24acf6-de0d-4da9-b845-8ee7306e4824.png">

You'll have to generate a link from Discord's Developer Portal for your bot. Navigate to your application's page, click on **OAuth2** from the sidebar and choose "URL Generator". Once you're in, follow these steps:

1. Tick `bot` and `application.commands` to enable the bot interface and allow IgKnite to receive slash command requests.

2. Then, make sure these permissions are allowed:

<img width="1025" alt="Screen Shot 2022-09-30 at 10 49 09 PM" src="https://user-images.githubusercontent.com/67194380/193318770-065a3a60-231e-4672-89cc-6f16ab95b2cb.png">

3. Scroll down and copy the generated URL. Finally, paste it in your browser, choose the server you want your bot to be in, voila!

**Comment by prasoonmhwr** [comment]
@hitblast Thanks again, I was able to integrate it , can you just quickly tell me how to use each command as I am facing error.

<img width="797" alt="Screenshot 2022-09-30 at 10 31 23 PM" src="https://user-images.githubusercontent.com/52622674/193320840-2265a854-ca60-4b9e-9209-b37512187519.png">

**Comment by hitblast** [comment]
> @hitblast Thanks again, I was able to integrate it , can you just quickly tell me how to use each command as I am facing error.
> 
> <img alt="Screenshot 2022-09-30 at 10 31 23 PM" width="797" src="https://user-images.githubusercontent.com/52622674/193320840-2265a854-ca60-4b9e-9209-b37512187519.png">

Oh most of those commands are still a little incomplete. To play a song, make sure you're in a voice / stage channel and then try again.

**Comment by prasoonmhwr** [comment]
> Oh most of those commands are still a little incomplete. To play a song, make sure you're in a voice / stage channel and then try again.

how to add songs on the queue

**Comment by prasoonmhwr** [comment]
@hitblast I have implemented this is this the desired behaviour

### New Implementation

https://user-images.githubusercontent.com/52622674/193335266-6b9856be-27f1-41f0-a28a-a08c13a9efd8.mov

---------------------
### Previous Implementation
<img width="424" alt="Screenshot 2022-09-30 at 10 45 47 PM" src="https://user-images.githubusercontent.com/52622674/193335491-7b08fe31-043a-4418-8183-1ed211cc9d0f.png">



Please let me know any changes are there :)

**Comment by hitblast** [comment]
@prasoonmhwr Excellent work! I really like the approach you've taken here. The last things you could do is check if all the buttons work as expected.

**Comment by prasoonmhwr** [comment]
@hitblast after checking all the buttons i will raise the PR, since its past 11:59pm in my country so it will be counted towards hacktoberfest i think

**Comment by hitblast** [comment]
Alright, thanks for your contribution!

**Comment by prasoonmhwr** [comment]
@hitblast I have created a PR for this

**Comment by hitblast** [comment]
Sure thing!
