### ISSUE TITLE
Make an interactive command for showing invites.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#40]
We all invite our friends to our Discord servers through time, and we can list the available invites using Discord's API within a command (and reuse them later on). This reduces our effort to click on buttons and see the current list of invites from the chat.

This issue requires you to:
- [ ] Make an `invites` command which shows all the available invites on the Discord server.
- [ ] Give it a proper description.

This issue also addresses some minimal requirements:
- [ ] The invites must not be shown in a "list of strings" manner. Instead, you can try using **selection menus** mentioned in Issue https://github.com/IgKniteDev/IgKnite/issues/38

**Comment by Trigstur** [comment]
Would love this into production! Could I be assigned?

**Comment by hitblast** [comment]
Thank you for reaching out! You've been assigned on this issue. I hope we can talk on Discord further about the Issue and stuff ;)

**Comment by Trigstur** [comment]
Implementation done => pull request filed under #49
