### ISSUE TITLE
Fixing some aspects of the `/now` slash command.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#48]
As most of you have probably guessed already, the `/now` slash command shows the details of the currently playing song (if any) in the chat. Even though it seems to be just about that, there are still some stuffs which need to be optimized:

- The command doesn't dynamically update after a song finishes playing. Meaning that even though the music player gets quiet, the command still shows that the player is actually *playing* something, when it's *not.*

- The command still lacks some functionality. Since `/volume` and `/skip` only work for the currently playing song, it might actually be a good idea to integrate these two commands into the `/now` command using buttons.

The issue is open to suggestions.

**Comment by delivey** [comment]
Hey, interested in working on this.

I think we should split this issue into 3 different ones:
1. Auto-updating the /now embed upon song ending, /skip being used, etc.
2. Adding a skip button to the /now embed.
3. Adding some sort of volume input to the /now embed.

2nd and 3rd should be easy, although we might run into some issues with the first one.
I think we should have some sort of expiration time for /now messages, meaning they will only be updated for an x amount of time, or until music stops playing. This will greatly improve performance compared to updating every single one that has ever been sent.

Let me know your thoughts on this.

**Comment by hitblast** [comment]
@delivey Well as of now, the now commands do not update upon song change. This is to ensure reduced memory load and stuff, so I think it's not needed to actually overthink.

Before any song is played, IgKnite shows the following message with the command: "There isn't anything being played at the moment."

When you do play a song, however, it presents you with the song details. 

The problem here is, once the song ends and the user triggers `/now` command again, it says that the player is still playing the song while it isn't. The expected fix here is to make the `/now` command say the very first message mentioned above.

Also, instead of showing volume input, we can display the volume (percentage) with a disabled, grey-ed out button. This is only for cosmetic purposes and the users won't be able to interact with it.

Thoughts?

**Comment by delivey** [comment]
Oh I see, misunderstood the issue.

My first thought was to use `inter.voice_state.is_playing`, but it seems like because of `disnake.FFmpegPCMAudio` the audio is marked as always playing. Will look around & try to fix this.

**Comment by delivey** [comment]
Maybe we can take advantage of the song queue, checking if it's empty, and if it is, stopping the audio & either setting a custom state or using `inter.voice_state.is_playing`.

**Comment by hitblast** [comment]
@delivey That's some genuine thought.

We could check for the length of the queue and if it's 0, we could apparently nullify the variables which define the state of the `/now` command. How about you try implementing it as a prototype and see how it works out?

**Comment by delivey** [comment]
Will do.

**Comment by delivey** [comment]
Running into a weird issue, even when using the official bot. Is this something on my end? 
![image](https://user-images.githubusercontent.com/35540227/193411286-011d6eca-cb93-4ea2-ab36-78089faba7e5.png)

**Comment by hitblast** [comment]
> Running into a weird issue, even when using the official bot. Is this something on my end? Didn't experience the issue a few hours ago.

Oh, this is an issue of the exception handler. If you aren't in any voice / stage channel while running the `/play` command then this occurs. Try joining one and executing the command again.

**Comment by delivey** [comment]
Ah, my bad.

Maybe we should create another issue which shows the error of "You're not in any voice channels" instead of this one?

**Comment by hitblast** [comment]
> Ah, my bad.
> 
> Maybe we should create another issue which shows the error of "You're not in any voice channels" instead of this one?

I'll create one :D

**Comment by delivey** [comment]
Came up with a very simple solution. Although I'm not sure if it's the most elegant.

Setting `is_playing` to True whenever the `self.voice.play` command is invoked, and setting `is_playing` to False whenever the next song is played or skipped. Seems to work. No issue with queues since the `is_playing` gets set to False and then instantly back to True.

What do you think about this? Should I create a PR or should we look for a more elegant solution? Takes up maybe 5-6 lines.

**Comment by delivey** [comment]
Found a pretty nice solution using a native method. Will make a PR.

**Comment by delivey** [comment]
Should I work on volume and skip now?

**Comment by hitblast** [comment]
> Should I work on volume and skip now?

@delivey Sure! Go ahead.

**Comment by delivey** [comment]
How's this for the UI? Let me know your thoughts.
![image](https://user-images.githubusercontent.com/35540227/193452974-e47c987c-afb4-456a-9148-973c40d703c4.png)

Also, what should happen after skipping the song? Update the message with new data from the /now command, whether that would be a new song or "There is nothing being played at the moment"?

**Comment by hitblast** [comment]
@delivey Neat! I have a few thoughts on this:

- How about keeping the volume button as `disabled=True`? This would block the user from interacting with it.
- Once skipped, we could just update the interaction message with the following code:
```python
await inter.response.edit_message(
    content='Song skipped!'  # only keeping the content and removing everything else (e.g. embed, view)
)
```

**Comment by delivey** [comment]
Sounds good. Will make a PR.

**Comment by hitblast** [comment]
> Sounds good. Will make a PR.

Alright. Since it's well over nighttime here, I'll try to review it quickly :P

**Comment by delivey** [comment]
#58
