### ISSUE TITLE
Try to error-handle the `/play` command.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#50]
If you ever tried to use IgKnite's music commands while actually *not* noticing that you're not in a voice (could be stage) channel, the following error occurs:

![193411286-011d6eca-cb93-4ea2-ab36-78089faba7e5](https://user-images.githubusercontent.com/67194380/193412600-d98c1db1-cc23-4aa4-aebb-19182e457272.png)

Maybe try to handle this one using the `ExceptionHandler` cog? Best of luck!

**Comment by prasoonmhwr** [comment]
please assign it to me :)

**Comment by hitblast** [comment]
@prasoonmhwr Done! Good luck :D

**Comment by prasoonmhwr** [comment]
@hitblast Is this the desired behaviour?


https://user-images.githubusercontent.com/52622674/193455308-d743def5-c87e-4714-9900-549661f18d43.mov

The message can be changed as per your requirement

**Comment by hitblast** [comment]
@prasoonmhwr Looks pretty neat. Could you please file a PR? I'd like to have a look at the source.

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr Looks pretty neat. Could you please file a PR? I'd like to have a look at the source.

done
