### ISSUE TITLE
Giving an upgrade to the exception handler.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#59]
IgKnite has an exception (or error, in simple terms) handler which tends to catch predefined errors and reply to their respective interactions. Here are some things to point out about it:

- It's been set up as **a cog** inside `cogs/exceptionhandler.py`.
- It sends the full error as the description and a custom message as the title for each exception handled.
- For now though, **it's pretty tiny.**

Notice the third point? Yeah, that's the problem here. If you'd like to contribute to this Issue, you'll have to:

- Thoroughly test each possible outcome for as many commands as you can.
- If an exception occurs for some unwanted reason, add it to the handler with an appropriate, cute little message.
- Push your changes once you're confident.

Testing all the commands might be a little difficult so don't rush! Take your time :D

**Comment by mpeiffer** [comment]
May I be assigned to this feature?

**Comment by hitblast** [comment]
@mpeiffer Sort of. Since IgKnite uses slash commands all around, I don't think there'll be much of those command-related exceptions. Assigning you :D

**Comment by mpeiffer** [comment]
Thanks for clarifying! I'll get started as soon as I can. :)

**Comment by mpeiffer** [comment]
I've put together a list of exceptions from running each of the IgKnite commands, and now I just need to test my changes. Do you have any documentation on self hosting IgKnite, or could you point me in the right direction for testing locally? No rush.

**Comment by TheShonuff** [comment]
@mpeiffer There are a few articles online on how to create a bot and get a token for discord. You’ll also need to create a Spotify dev account and get a token. Put those tokens and ids in the .env.sample and rename to .env… you should be able to run the main.py file and see the bot populate on your server

**Comment by mpeiffer** [comment]
Awesome, thank you for the help!

**Comment by hitblast** [comment]
@mpeiffer Hello! Hope all's going well.

**Comment by mpeiffer** [comment]
@hiblast Hello! I unfortunately haven't had a lot of free time the past few days, but I was able to set up the bot for testing and should be able to test my changes today. Thanks for checking in!

**Comment by hitblast** [comment]
@mpeiffer Thanks for notifying me about your state too! Glad that you're taking time to make the feature work. Appreciate it 👍
