### ISSUE TITLE
Switch to min & max value validation built-into Discord.

### ISSUE THREAD

**Issue by relby** [IgKniteDev/IgKnite#62]
Commands such as `audit`, `volume` etc. have integer options. And we have the validation for them in the code, but Discord has its own [validation](https://docs.disnake.dev/en/stable/api.html?highlight=option#disnake.Option) of min and max values in the slash commands. I think it's reasonable to switch to it.
If it's fine I can send a pull request to this issue.

**Comment by hitblast** [comment]
@relby Understandable. How about I assign you on this issue and you send the PR over? Will be well over glad to see your work :)
