### ISSUE TITLE
Proof-reading the README.md file.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#68]
This issue requires you to:

- Go through the [README.md](https://github.com/IgKniteDev/IgKnite/blob/main/README.md) file located in the root of IgKnite.
- Change the format of language wherever needed / the text becomes misleading.
- Add some of your own magic :D
- Make a pull request and mention this issue.

**Comment by dapoadedire** [comment]
Can you assign this to me, please?

**Comment by hitblast** [comment]
@dapoadedire There you go!
