### ISSUE TITLE
Making a command to permanently reset a channel.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#69]
How about making a command which resets a channel's contents permanently? The logic could go like this:

- Copy the channel metadata e.g. channel name, description, the name of the category it's in and the permissions.
- Delete the original channel.
- Make a new channel with the exact same metadata.
- Finally put the channel into its previous category, if any.

I would really love to see your thoughts on this. Good luck!

**Comment by amoghrajesh** [comment]
This is a good idea. @hitblast I would like to work on this. Can you tell me how to get started and assign to me?

**Comment by hitblast** [comment]
> This is a good idea. @hitblast I would like to work on this. Can you tell me how to get started and assign to me?

@amoghrajesh Thanks for showing your interest! In order to start properly, make sure you set up the development environment properly. 

- Rename the `.env.sample` to `.env` and keep the secrets there.

- Install the dependencies from the `requirements.txt` file and make sure you have **ffmpeg** installed for voice commands. Alternatively, you can build a docker image (`Dockerfile` included) and test the bot from there.

- In order to get full-fledged instructions on how to add a command, make sure to read the contribution guidelines from **CONTRIBUTING.md** and you're done!

Hopefully this will make sense. Also, assigning you ;)

**Comment by hitblast** [comment]
> Thank you @hitblast 
> Can you help me with the starting point in the code?

@amoghrajesh Sure enough! Let me know what problems you're facing.

**Comment by amoghrajesh** [comment]
No problems yet. Wanted to know where the code is present for me to start

**Comment by hitblast** [comment]
> No problems yet. Wanted to know where the code is present for me to start

Oh, the cog for error handling is located in `cogs/exceptionhandler.py`

**Comment by TheShonuff** [comment]
Don't want to step on any toes here. Pretty new to this collaborative environment. I was able to implement and test a version of this feature on Text Channels. I submitted a PR... Maybe @amoghrajesh can use this as a jumping off point?

**Comment by hitblast** [comment]
The issue will be closed shortly once I'm done proof-reading the PR :)
