### ISSUE TITLE
Tuning the `/queue` slash command.

### ISSUE THREAD

**Issue by delivey** [IgKniteDev/IgKnite#70]
### What would you like to share?

I feel like the `/queue` command could use some improvements. Here are some of them:
1. Display the current song in the queue list. Right now when you use /queue the image below is shown: 
![image](https://user-images.githubusercontent.com/35540227/193850639-5092da28-e230-448f-942e-4bf6679f2cc4.png)
Replacing "Choose your song" with `<current song> (CURRENT)` and setting it to disabled might be useful for users. Adding an image and song title like with `/now` or when selecting a song from the queue could also be an option.
2. Letting a user play a song straight from the queue.
This would work by adding another button - "Play" next to the "Shuffle" Button which would skip all songs in the queue until it reaches the desired song.
3. "Remove" button next to the "Shuffle" button which would allow you to remove a song from the queue without using `/rmqueue`

Let me know your thoughts on this.

**Comment by hitblast** [comment]
I really love your thoughts on **option 2 and 3**, but I kinda disagree on the first one cause that'd sort of kill `/queue` in the process.

**Comment by delivey** [comment]
Yes, I would. Please assign me on this.

**Comment by hitblast** [comment]
Alright! Good luck :)

**Comment by delivey** [comment]
Running into a bit of trouble with the implementation of creating a button upon select callback and feeding the value to the button's callback function. Just an update, will figure it out myself.

**Comment by hitblast** [comment]
@delivey Glad to have the update! I hope you'll be able to do it.

**Comment by TheShonuff** [comment]
@delivey I'm thinking about hopping on this issue. Let's collaborate

**Comment by delivey** [comment]
@TheShonuff Would be down to collaborate.

Can you figure out a way to delete select options from the dropdown after the "Remove from queue" button is clicked? Trying it myself, but nothing is working right now.

Here's the code: https://github.com/delivey/IgKnite/tree/queue_tune

Keep in mind it's very messy, trying to get a prototype working before I clean it up.

**Comment by delivey** [comment]
Right now, I have two approaches to the problem of updating the dropdown after removing a song:
1. Edit the original message and just change it to "Removed".
2. Delete the original queue message and send a new one.

First one would be way easier, but the second one would be more user friendly.
What do you think?  @hitblast

**Comment by hitblast** [comment]
@delivey You could take a similar approach as the `/now` command :) Thanks for brainstorming about it.

**Comment by delivey** [comment]
Alright, taking the first approach.

Should have a PR ready tomorrow.

**Comment by hitblast** [comment]
> Working on a way to skip multiple songs for the Play button.
> 
> Running a loop and calling the `voice_state.skip()` function doesn't work, pretty sure there has to be a delay for it to properly register. Looking at other solutions.

How about instead of skipping it, we prioritize the music within the list by changing its index (popping out and placing it in front) and then skipping the current song?

**Comment by delivey** [comment]
Yeah, I'll do that. Thanks.

**Comment by delivey** [comment]
Should we close the issue?

**Comment by hitblast** [comment]
Ah I forgot to reference it, my bad :P
