### ISSUE TITLE
[DOCS] License related

### ISSUE THREAD

**Issue by kailashchoudhary11** [IgKniteDev/IgKnite#76]
### Description

Why is the license pasted everywhere in all the files? It is quite annoying.

### Additional information

I would like to remove the License text from all the python file, since there is already a dedicated file for the license. Also if you want to mention everywhere about the license we can mention the link of the License file wherever required. Just copy pasting the same thing everywhere is not a good idea.

**Comment by hitblast** [comment]
@kailashchoudhary11 How about you put the GitHub link of the LICENSE file within those docstrings which contain the actual license? Feel free to work on it as needed.

**Comment by kailashchoudhary11** [comment]
Thank you for assigning. I will try to resolve this as soon as possible.
