### ISSUE TITLE
Tuning the `/ping` slash command.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#78]
We all can see and execute different types of 'ping' commands with most Discord bots. These commands tend to show vital information about a bot's uptime, statistics and more. 

IgKnite's `/ping` slash command only contains two fields for now:

- System Latency
- API Latency

... which seemingly seems pretty incomplete. How about we add some more fields like uptime and performance?

**Comment by l3xi42** [comment]
can you assign it to me pls

**Comment by hitblast** [comment]
@l3xi42 There you go!
