### ISSUE TITLE
[DOCS] Add emoji/icons to README.md

### ISSUE THREAD

**Issue by Oceaneyes123** [IgKniteDev/IgKnite#81]
### Description

Missing emoji 

❤️ instead of <3 

I'll work on it, please assign to me

**Comment by hitblast** [comment]
Thanks for your approach but we're already working on it! Maybe try with something else?

**Comment by Oceaneyes123** [comment]
This is closed and this is spammed, why assign? @hitblast

**Comment by hitblast** [comment]
@Oceaneyes123 Keeping track of stuff!
