### ISSUE TITLE
Adding informative fields to the `/ping` slash command.

### ISSUE THREAD

**Issue by hitblast** [IgKniteDev/IgKnite#83]
The 'ping' command, in the case of most Discord bots, tends to show vital information related to the uptime, performance and latency. For now, IgKnite's `/ping` command displays only two fields:

- System Latency
- API Latency

How about adding more? Think!

Bloopers: The PR #78 failed to do so, and thus was reverted right after merging.

**Comment by furtidev** [comment]
Can you assign me to this?

**Comment by hitblast** [comment]
@furtidev There you go!
